# This is a basic workflow to help you get started with Actions

name: ESLint

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.1.0
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '12.13.0'
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Package Install
        run: npm install
      - name: fetch
        env:
          COMMIT_AFTER: ${{ github.event.after }}
          COMMIT_BEFORE: ${{ github.event.before }}
          TARGET_BRANCH: ${{ github.base_ref }}
        run: git fetch --depth 1 origin ${TARGET_BRANCH}
      - name: ESLint
        env:
          COMMIT_AFTER: ${{ github.event.after }}
          COMMIT_BEFORE: ${{ github.event.before }}
          run: |
          export GIT_DIFF=$(git diff-tree --no-commit-id --name-only -r ${COMMIT_AFTER})
          echo "${GIT_DIFF}"
          if [[ -n "${GIT_DIFF}" ]]; then
              echo "${GIT_DIFF}" \
                  | grep '\.js$' | xargs node_modules/eslint/bin/eslint.js -c .eslintrc.js --ignore-path .eslintignore
          else
              echo "No JavaScript files to lint. Moving on..."
          fi
